/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Manrope', 'Inter', 'system-ui', 'sans-serif'],
        headline: ['Manrope'],
        body: ['Manrope'],
        label: ['Manrope'],
      },
      colors: {
        "surface-container": "#002427",
        "surface-tint": "#9ecfd7",
        "surface-variant": "#133a3e",
        "on-tertiary": "#343020",
        "tertiary": "#cec6af",
        "secondary-fixed": "#c2eaee",
        "on-secondary-container": "#99bfc4",
        "error-container": "#93000a",
        "background": "#001719",
        "primary-fixed-dim": "#9ecfd7",
        "primary-container": "#3f6f76",
        "on-error": "#690005",
        "primary-fixed": "#b9ebf3",
        "on-primary": "#00363c",
        "secondary-fixed-dim": "#a7cdd2",
        "on-surface-variant": "#c0c8c9",
        "tertiary-container": "#6d6855",
        "on-tertiary-fixed": "#1f1c0d",
        "surface-container-high": "#042f33",
        "on-primary-fixed": "#001f23",
        "outline-variant": "#404849",
        "on-tertiary-fixed-variant": "#4b4735",
        "on-tertiary-container": "#f0e8cf",
        "outline": "#8a9293",
        "primary": "var(--primary)",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#002023",
        "tertiary-fixed-dim": "#cec6af",
        "surface-container-highest": "#133a3e",
        "surface-container-lowest": "#001113",
        "on-primary-container": "#bef0f8",
        "surface-bright": "#183f42",
        "tertiary-fixed": "#eae2ca",
        "on-background": "#c2eaee",
        "secondary": "#a7cdd2",
        "on-primary-fixed-variant": "#1a4d54",
        "surface": "#001719",
        "on-surface": "#c2eaee",
        "inverse-surface": "#c2eaee",
        "inverse-primary": "#35656c",
        "on-secondary-fixed": "#002023",
        "inverse-on-surface": "#0d3639",
        "secondary-container": "#2a4f53",
        "surface-dim": "#001719",
        "on-secondary": "#0d3639",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#274c50",

        // Mantener nombres antiguos para retrocompatibilidad
        "agro-primary": "#2F5458",
        "agro-secondary": "#3F6F76",
        "agro-accent": "#E8E0C8",
        "agro-navy": "#001719",
        "agro-ocean": "#3F6F76",
        "agro-sky": "#9ecfd7",
        "agro-midnight": "#001113",
        "agro-charcoal": "#002427",
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
        '6xl': '3.5rem',
      },
      boxShadow: {
        'premium': '0 20px 50px -12px rgba(0, 0, 0, 0.5)',
        'blue-accent': '0 0 25px -5px rgba(63, 111, 118, 0.2)',
        'blue-accent-lg': '0 0 50px -10px rgba(63, 111, 118, 0.4)',
        'teal-glow': '0 0 20px rgba(63, 111, 118, 0.5)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      }
    },
  },
  plugins: [],
};